### ISSUE TITLE
Library not loaded: @rpath/libnetcdf.11.dylib

### ISSUE THREAD

**Issue by roxyboy** [NCAR/pynio#4]
To whom it may concern,

I have tried installing pynio on my Mac osX system by running `conda install -c dbrown pynio`. The results give:

```
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
Solving package specifications: .........

Package plan for installation in environment /Users/UchidaTakaya/anaconda/envs/PyNIO:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pynio-1.5.0beta            |      np110py27_8         3.1 MB

The following NEW packages will be INSTALLED:

    szip:  2.1-0                

The following packages will be UPDATED:

    pynio: 1.4.3-np110py27_3 --> 1.5.0beta-np110py27_8

Proceed ([y]/n)? y

Fetching packages ...
pynio-1.5.0bet 100% |#############################################################################| Time: 0:00:01   2.05 MB/s
Extracting packages ...
[      COMPLETE      ]|################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|################################################################################################| 100%
```

so it seems to be installed. However, when I try to import Nio, an error shows up as:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Nio.py", line 83, in <module>
    from nio import *
ImportError: dlopen(./nio.so, 2): Library not loaded: @rpath/libnetcdf.11.dylib
  Referenced from: /Users/UchidaTakaya/anaconda/envs/PyNIO/lib/python2.7/site-packages/PyNIO/nio.so
  Reason: image not found
``` 

I looked for the libnetcdf.11.dylib library by running `otool -L /(package_path)/PyNIO/nio.so`, which shows that it is downloaded:

```
/Users/UchidaTakaya/anaconda/envs/PyNIO/lib/python2.7/site-packages/PyNIO/nio.so:
	@rpath/libjpeg.8.dylib (compatibility version 13.0.0, current version 13.0.0)
	@rpath/libpng16.16.dylib (compatibility version 34.0.0, current version 34.0.0)
	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	@rpath/libnetcdf.11.dylib (compatibility version 12.0.0, current version 12.0.0)
	@rpath/libhdf5_hl.10.dylib (compatibility version 11.0.0, current version 11.2.0)
	@rpath/libhdf5.10.dylib (compatibility version 12.0.0, current version 12.0.0)
	@rpath/libcurl.4.dylib (compatibility version 9.0.0, current version 9.0.0)
	@rpath/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libgdal.20.dylib (compatibility version 21.0.0, current version 21.2.0)
	@rpath/./libproj.9.dylib (compatibility version 10.0.0, current version 10.0.0)
	@rpath/./libiconv.2.dylib (compatibility version 8.0.0, current version 8.1.0)
	@rpath/./libgfortran.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	@rpath/./libstdc++.6.dylib (compatibility version 7.0.0, current version 7.19.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
	@rpath/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

Could you please tell me how to resolve this issue? Thank you very much for your attention and support.

**Comment by khallock** [comment]
Hi,

Could you please run the command "conda list" with your PyNIO environment activated and post the output? I'm curious to see which versions of the dependency packages are installed.

Thanks,
Kevin

**Comment by ajoros** [comment]
I have the same issue... @khallock here is my conda list output:

```
ajoros @ ~/Dropbox/AIC/NWP/MOSarchive/GFSMOS/rawGFSdata * master
 [4] → conda list
# packages in environment at /Users/ajoros/anaconda/envs/py2711:
#
appnope                   0.1.0                    py27_0    defaults
backports-abc             0.4                       <pip>
backports.shutil-get-terminal-size 1.0.0                     <pip>
backports.shutil_get_terminal_size 1.0.0                    py27_0    conda-forge
backports.ssl-match-hostname 3.5.0.1                   <pip>
backports_abc             0.4                      py27_0    defaults
blas                      1.1                    openblas    conda-forge
bokeh                     0.12.0                   py27_0    defaults
boto3                     1.3.1                    py27_0    defaults
botocore                  1.4.37                   py27_0    defaults
bottleneck                1.1.0               np111py27_0    defaults
click                     6.6                      py27_0    conda-forge
cloudpickle               0.2.1                    py27_2    conda-forge
curl                      7.49.1                        0    conda-forge
cyordereddict             1.0.0                    py27_0    conda-forge
dask                      0.10.1                   py27_1    conda-forge
decorator                 4.0.10                   py27_0    conda-forge
distributed               1.11.2                   py27_0    conda-forge
docutils                  0.12                     py27_2    defaults
expat                     2.1.0                         1    conda-forge
freexl                    1.0.2                         1    conda-forge
futures                   3.0.5                    py27_0    defaults
g2clib                    1.5.0                         4    conda-forge
gdal                      1.11.4             np111py27_10    conda-forge
geos                      3.4.2                         2    conda-forge
giflib                    5.1.2                         1    conda-forge
h5netcdf                  0.2.2                    py27_0    conda-forge
h5py                      2.6.0               np111py27_4    conda-forge
hdf4                      4.2.11                        4    conda-forge
hdf5                      1.8.17                        2    conda-forge
hdfeos2                   2.19.1                        4    conda-forge
hdfeos5                   5.1.15                        5    conda-forge
icu                       56.1                          4    conda-forge
ipython                   4.2.0                    py27_0    conda-forge
ipython-genutils          0.1.0                     <pip>
ipython_genutils          0.1.0                    py27_0    defaults
jasper                    1.900.1                       2    conda-forge
jinja2                    2.8                      py27_1    defaults
jmespath                  0.9.0                    py27_0    conda-forge
jpeg                      9b                            0    conda-forge
json-c                    0.12                          0    conda-forge
krb5                      1.14.2                        0    conda-forge
libgcc                    4.8.5                         1    defaults
libgdal                   1.11.2                        1    defaults
libgfortran               3.0.0                         0    conda-forge
libiconv                  1.14                          2    conda-forge
libnetcdf                 4.4.0                         1    conda-forge
libpng                    1.6.23                        0    conda-forge
libspatialite             4.3.0a                        8    conda-forge
libtiff                   4.0.6                         6    conda-forge
libxml2                   2.9.3                         9    conda-forge
locket                    0.2.0                    py27_1    defaults
markupsafe                0.23                     py27_2    defaults
msgpack-python            0.4.6                    py27_0    defaults
netcdf4                   1.2.4               np111py27_2    conda-forge
numpy                     1.11.1          py27_blas_openblas_200  [blas_openblas]  conda-forge
openblas                  0.2.18                        3    conda-forge
openjpeg                  2.1.0                         5    conda-forge
openssl                   1.0.2h                        1    defaults
pandas                    0.18.1              np111py27_0    conda-forge
partd                     0.3.4                    py27_0    conda-forge
pathlib2                  2.1.0                    py27_0    conda-forge
pexpect                   4.1.0                    py27_0    conda-forge
pickleshare               0.7.3                    py27_0    conda-forge
pip                       8.1.2                    py27_0    conda-forge
postgresql                9.5.3                    py27_0    conda-forge
proj.4                    4.9.2                         0    conda-forge
proj4                     4.9.2                         0    defaults
prompt-toolkit            1.0.3                     <pip>
prompt_toolkit            1.0.3                    py27_0    conda-forge
psutil                    4.3.0                    py27_0    conda-forge
ptyprocess                0.5.1                    py27_0    conda-forge
pygments                  2.1.3                    py27_0    defaults
pynio                     1.5.0_beta20160623     np111py27_0    dbrown
python                    2.7.12                        1    defaults
python-dateutil           2.5.3                    py27_0    defaults
python.app                1.2                      py27_4    <unknown>
pytz                      2016.6.1                 py27_0    defaults
pyyaml                    3.11                     py27_4    defaults
readline                  6.2                           2    <unknown>
requests                  2.10.0                   py27_0    conda-forge
s3fs                      0.0.6                    py27_0    conda-forge
scipy                     0.17.1          np111py27_blas_openblas_202  [blas_openblas]  conda-forge
setuptools                23.0.0                   py27_0    conda-forge
simplegeneric             0.8.1                    py27_1    defaults
singledispatch            3.4.0.3                  py27_0    defaults
six                       1.10.0                   py27_0    defaults
sqlite                    3.13.0                        1    conda-forge
ssl_match_hostname        3.5.0.1                  py27_0    conda-forge
tblib                     1.3.0                    py27_0    defaults
tk                        8.5.18                        0    <unknown>
toolz                     0.8.0                    py27_0    conda-forge
tornado                   4.3                      py27_1    defaults
tqdm                      4.7.6                    py27_0    conda-forge
traitlets                 4.2.2                    py27_0    conda-forge
wcwidth                   0.1.7                    py27_0    conda-forge
wheel                     0.29.0                   py27_0    defaults
xarray                    0.7.2                    py27_0    conda-forge
xerces-c                  3.1.4                         2    conda-forge
xz                        5.2.2                         0    conda-forge
yaml                      0.1.6                         0    <unknown>
zlib                      1.2.8                         3    defaults
(py2711)
```

**Comment by khallock** [comment]
Hi @ajoros,

Thanks for the "conda list" output. I see that you are using some conda-forge packages in your py2711 conda environment. We have definitely noticed that installing packages from multiple conda channels (dbrown and conda-forge in this case) into the same environment can cause bizarre dependency issues. Specifically, I suspect that the particular "libnetcdf" package (conda-forge) that is installed may have been built with different options than the "pynio" package (dbrown) expects from "libnetcdf" (I believe @david-ian-brown has historically built PyNIO against the "libnetcdf" package from the defaults channel).

We strive to make PyNIO as compatible as possible with other conda packages, but sometimes resolving the dependencies for PyNIO and other complex packages simultaneously can result situations like this.

There is a version of PyNIO that has been included in the conda-forge channel, although we are not the maintainers of that package. This build appears to be based on commit 0f6c689, so it is 4 commits (3 months) out of date. Regardless, I believe that build may work better for you at the moment since you are already using other software from the conda-forge channel.

The following commands should overwrite the currently installed version of the "pynio" package with the conda-forge version (you may need to remove the existing "pynio" package first):
```
conda remove pynio         #may not be necessary
conda install -n py2711 -c conda-forge pynio
```

I hope this helps!

Kevin

**Comment by ajoros** [comment]
OK, thanks @khallock I think that fixed that issue...
But now I get this error (Is it because im missing a library?):
```
ImportError: dlopen(/Users/ajoros/anaconda/envs/py2711/lib/python2.7/site-packages/PyNIO/nio.so, 2): Library not loaded: @loader_path/./libnetcdf.7.dylib
  Referenced from: /Users/ajoros/anaconda/envs/py2711/lib/libgdal.1.dylib
  Reason: image not found
```

**Comment by ajoros** [comment]
Additionally I did a clean install of an xarray environment [And still get the same error] using python 2.7 and xarray using:
`conda create -n py2711xr python=2.7.11 xarray` and the conda list results in:

```
# packages in environment at /Users/ajoros/anaconda/envs/py2711xr:
#
appnope                   0.1.0                    py27_0    defaults
backports-abc             0.4                       <pip>
backports.shutil-get-terminal-size 1.0.0                     <pip>
backports.shutil_get_terminal_size 1.0.0                    py27_0    conda-forge
backports.ssl-match-hostname 3.5.0.1                   <pip>
backports_abc             0.4                      py27_0    defaults
bokeh                     0.12.0                   py27_0    defaults
boto3                     1.3.1                    py27_0    defaults
botocore                  1.4.37                   py27_0    defaults
bottleneck                1.0.0               np110py27_1    defaults
click                     6.6                      py27_0    conda-forge
cloudpickle               0.2.1                    py27_2    conda-forge
curl                      7.49.1                        0    conda-forge
cyordereddict             1.0.0                    py27_0    conda-forge
dask                      0.10.1                   py27_1    conda-forge
decorator                 4.0.10                   py27_0    conda-forge
distributed               1.11.2                   py27_0    conda-forge
docutils                  0.12                     py27_2    defaults
expat                     2.1.0                         1    conda-forge
freexl                    1.0.2                         1    conda-forge
futures                   3.0.5                    py27_0    defaults
g2clib                    1.5.0                         4    conda-forge
gdal                      2.1.0               np110py27_7    conda-forge
geos                      3.4.2                         2    conda-forge
giflib                    5.1.2                         1    conda-forge
h5netcdf                  0.2.2                    py27_0    conda-forge
h5py                      2.6.0               np110py27_4    conda-forge
hdf4                      4.2.11                        4    conda-forge
hdf5                      1.8.17                        2    conda-forge
hdfeos2                   2.19.1                        4    conda-forge
hdfeos5                   5.1.15                        5    conda-forge
icu                       56.1                          4    conda-forge
ipython                   5.0.0                    py27_0    conda-forge
ipython-genutils          0.1.0                     <pip>
ipython_genutils          0.1.0                    py27_0    defaults
jasper                    1.900.1                       2    conda-forge
jinja2                    2.8                      py27_1    defaults
jmespath                  0.9.0                    py27_0    conda-forge
jpeg                      9b                            0    conda-forge
json-c                    0.12                          0    conda-forge
kealib                    1.4.6                         2    conda-forge
krb5                      1.14.2                        0    conda-forge
libgcc                    4.8.5                         1    defaults
libiconv                  1.14                          2    conda-forge
libnetcdf                 4.4.1                         0    defaults
libpng                    1.6.23                        0    conda-forge
libspatialite             4.3.0a                        8    conda-forge
libtiff                   4.0.6                         6    conda-forge
libxml2                   2.9.3                         9    conda-forge
locket                    0.2.0                    py27_1    defaults
markupsafe                0.23                     py27_2    defaults
mkl                       11.3.3                        0    defaults
msgpack-python            0.4.6                    py27_0    defaults
netcdf4                   1.2.4               np110py27_2    conda-forge
numpy                     1.10.4                   py27_2    defaults
openjpeg                  2.1.0                         5    conda-forge
openssl                   1.0.2h                        1    defaults
pandas                    0.18.1              np110py27_0    conda-forge
partd                     0.3.4                    py27_0    conda-forge
pathlib2                  2.1.0                    py27_0    conda-forge
pexpect                   4.1.0                    py27_0    conda-forge
pickleshare               0.7.3                    py27_0    conda-forge
pip                       8.1.2                    py27_0    conda-forge
postgresql                9.5.3                    py27_0    conda-forge
proj.4                    4.9.2                         0    conda-forge
prompt-toolkit            1.0.3                     <pip>
prompt_toolkit            1.0.3                    py27_0    conda-forge
psutil                    4.3.0                    py27_0    conda-forge
ptyprocess                0.5.1                    py27_0    conda-forge
pygments                  2.1.3                    py27_0    defaults
pynio                     1.5.0beta           np110py27_0    conda-forge
python                    2.7.12                        1    defaults
python-dateutil           2.5.3                    py27_0    defaults
python.app                1.2                      py27_4    <unknown>
pytz                      2016.6.1                 py27_0    defaults
pyyaml                    3.11                     py27_4    defaults
readline                  6.2                           2    <unknown>
requests                  2.10.0                   py27_0    conda-forge
s3fs                      0.0.6                    py27_0    conda-forge
scipy                     0.17.1              np110py27_1    defaults
setuptools                23.0.0                   py27_0    conda-forge
simplegeneric             0.8.1                    py27_1    defaults
singledispatch            3.4.0.3                  py27_0    defaults
six                       1.10.0                   py27_0    defaults
sqlite                    3.13.0                        1    conda-forge
ssl_match_hostname        3.5.0.1                  py27_0    conda-forge
tblib                     1.3.0                    py27_0    defaults
tk                        8.5.18                        0    <unknown>
toolz                     0.8.0                    py27_0    conda-forge
tornado                   4.3                      py27_1    defaults
traitlets                 4.2.2                    py27_0    conda-forge
wcwidth                   0.1.7                    py27_0    conda-forge
wheel                     0.29.0                   py27_0    defaults
xarray                    0.7.2                    py27_0    conda-forge
xerces-c                  3.1.4                         2    conda-forge
xz                        5.2.2                         0    conda-forge
yaml                      0.1.6                         0    <unknown>
zlib                      1.2.8                         3    defaults
(py2711xr)
```

**Comment by ajoros** [comment]
I may have solved it. This was my order of installation, even after adding the conda-forge channel:

```
conda create -n py2711xr python=2.7
conda config --add channels conda-forge
source activate py2711xr
conda install xarray dask netCDF4 bottleneck
```

I also installed ipython to test out the grb loading process and executed this line:

`test=xr.open_dataset('gfs.t12z.pgrb2.0p25.f060.grb', engine='pynio')
`

The variable "test" now outputs the following: 
```
Out[5]: 
<xarray.Dataset>
Dimensions:                   (lat_0: 721, lon_0: 1440, lv_AMSL1: 3, lv_DBLL12: 4, lv_HTGL2: 3, lv_HTGL4: 2, lv_HTGL7: 3, lv_ISBL0: 31, lv_ISBL10: 17, lv_ISBL11: 19, lv_ISBL6: 21, lv_ISBL8: 26, lv_PVL3: 2, lv_SIGL5: 4, lv_SPDL9: 2)
Coordinates:
  * lv_ISBL11                 (lv_ISBL11) float32 10000.0 15000.0 20000.0 ...
  * lv_ISBL10                 (lv_ISBL10) float32 100.0 200.0 300.0 500.0 ...
  * lv_ISBL8                  (lv_ISBL8) float32 1000.0 2000.0 3000.0 5000.0 ...
  * lv_HTGL4                  (lv_HTGL4) float32 2.0 80.0
  * lv_ISBL0                  (lv_ISBL0) float32 100.0 200.0 300.0 500.0 ...
  * lv_HTGL7                  (lv_HTGL7) float32 10.0 80.0 100.0
  * lv_HTGL2                  (lv_HTGL2) float32 2.0 80.0 100.0
  * lv_ISBL6                  (lv_ISBL6) float32 10000.0 15000.0 20000.0 ...
  * lat_0                     (lat_0) float32 90.0 89.75 89.5 89.25 89.0 ...
  * lon_0                     (lon_0) float32 0.0 0.25 0.5 0.75 1.0 1.25 1.5 ...
  * lv_PVL3                   (lv_PVL3) float32 -2e-06 2e-06
  * lv_AMSL1                  (lv_AMSL1) float32 1829.0 2743.0 3658.0
  * lv_DBLL12                 (lv_DBLL12) int64 0 1 2 3
  * lv_SIGL5                  (lv_SIGL5) int64 0 1 2 3
  * lv_SPDL9                  (lv_SPDL9) int64 0 1
Data variables:
    APCP_P8_L1_GLL0_acc6h     (lat_0, lon_0) float64 0.0 0.0 0.0 0.0 0.0 0.0 ...
    TOZNE_P0_L200_GLL0        (lat_0, lon_0) float64 301.8 301.8 301.8 301.8 ...
    PRES_P0_L242_GLL0         (lat_0, lon_0) float64 nan nan nan nan nan nan ...
    VFLX_P8_L1_GLL0_avg6h     (lat_0, lon_0) float64 -0.001 -0.001 -0.001 ...
    HGT_P0_L100_GLL0          (lv_ISBL0, lat_0, lon_0) float64 4.971e+04 ...
    VVEL_P0_L100_GLL0         (lv_ISBL6, lat_0, lon_0) float64 0.0 0.0 0.0 ...
    ULWRF_P8_L1_GLL0_avg6h    (lat_0, lon_0) float64 313.0 313.0 313.0 313.0 ...
    UGRD_P0_L6_GLL0           (lat_0, lon_0) float64 -3.6 -3.7 -3.7 -3.7 ...
    HGT_P0_L7_GLL0            (lat_0, lon_0) float64 1.003e+04 1.003e+04 ...
```
