### ISSUE TITLE
Can not import pynio on yellowstone// libmfhdf.so.0: cannot open shared object file

### ISSUE THREAD

**Issue by Yefee** [NCAR/pynio#5]
Hi, 

I installed miniconda on yellowstone and tried tp install conda on both dbrown and conda-forge channel. Both can not import pynio :-(

the error message:
```
yslogin1:~> python -c "import nio"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: libmfhdf.so.0: cannot open shared object file: No such file or directory
```
below is my conda list

```
backports                 1.0                      py27_0
backports_abc             0.4                      py27_0
bokeh                     0.11.1                   py27_0
boto3                     1.3.1                    py27_0
cairo                     1.12.18                       6
chest                     0.2.3                    py27_0
cloog                     0.18.0                        0
cloudpickle               0.2.1                    py27_0
conda                     4.1.11                   py27_0
botocore                  1.4.34                   py27_0    conda-forge
bottleneck                1.0.0               np110py27_0    conda-forge
click                     6.6                      py27_0    conda-forge
conda-env                 2.5.2                    py27_0    conda-forge
cyordereddict             1.0.0                    py27_1    conda-forge
dask                      0.10.1                   py27_1    conda-forge
distributed               1.11.2                   py27_0    conda-forge
freexl                    1.0.2                         1    conda-forge
gdal                      1.11.4             np110py27_10    conda-forge
giflib                    5.1.2                         1    conda-forge
h5netcdf                  0.2.2                    py27_0    conda-forge
h5py                      2.6.0               np110py27_4    conda-forge
hdf5                      1.8.17                        2    conda-forge
jmespath                  0.9.0                    py27_0    conda-forge
jpeg                      9b                            0    conda-forge
json-c                    0.12                          0    conda-forge
krb5                      1.14.2                        0    conda-forge
libnetcdf                 4.4.0                         2    conda-forge
libspatialite             4.3.0a                        8    conda-forge
libtiff                   4.0.6                         5    conda-forge
netcdf4                   1.2.4               np110py27_2    conda-forge
openjpeg                  2.1.0                         5    conda-forge
pillow                    3.2.0                    py27_1    conda-forge
postgresql                9.5.3                    py27_0    conda-forge
psutil                    4.3.0                    py27_0    conda-forge
pynio                     1.5.0               np110py27_7    conda-forge
s3fs                      0.0.6                    py27_0    conda-forge
xarray                    0.7.2                    py27_1    conda-forge
configparser              3.5.0                    py27_0
curl                      7.45.0                        0
cycler                    0.10.0                   py27_0
g2clib                    1.5.0                         1    dbrown
hdf4                      4.2.11                        1    dbrown
hdfeos2                   2.19.1                        1    dbrown
hdfeos5                   5.1.15                        1    dbrown
jasper                    1.900.1                       1    dbrown
libgdal                   2.0.2                 geos342_3    dbrown
libiconv                  1.14                          1    dbrown
szip                      2.1                           1    dbrown
decorator                 4.0.9                    py27_0
docutils                  0.12                     py27_2
entrypoints               0.2.2                    py27_0
expat                     2.1.0                         0
fontconfig                2.11.1                        5
freetype                  2.5.5                         0
funcsigs                  1.0.0                    py27_0
functools32               3.2.3.2                  py27_0
futures                   3.0.5                    py27_0
gcc                       4.8.5                         6
get_terminal_size         1.0.0                    py27_0
gmp                       5.1.2                         2
heapdict                  1.0.0                    py27_0
ipykernel                 4.3.1                    py27_0
ipython                   4.2.0                    py27_0
ipython_genutils          0.1.0                    py27_0
ipywidgets                4.1.1                    py27_0
isl                       0.12.2                        0
jbig                      2.1                           0
jinja2                    2.8                      py27_0
jsonschema                2.5.1                    py27_0
jupyter                   1.0.0                    py27_3
jupyter_client            4.3.0                    py27_0
jupyter_console           5.0.0                    py27_0
jupyter_core              4.1.0                    py27_0
kealib                    1.4.5                         0
libgcc                    5.2.0                         0
libgfortran               3.0.0                         1
libpng                    1.6.17                        0
libsodium                 1.0.10                        0
libxml2                   2.9.2                         0
libxslt                   1.1.28                        0
locket                    0.2.0                    py27_0
lxml                      3.6.0                    py27_0
markupsafe                0.23                     py27_0
matplotlib                1.5.1               np110py27_0
mistune                   0.7.2                    py27_0
mkl                       11.3.1                        0
mock                      2.0.0                    py27_0
mpc                       1.0.1                         0
mpfr                      3.1.2                         0
msgpack-python            0.4.7                    py27_0
nbconvert                 4.2.0                    py27_0
nbformat                  4.0.1                    py27_0
nose                      1.3.7                    py27_0
notebook                  4.2.1                    py27_0
numpy                     1.10.4                   py27_1
openssl                   1.0.2g                        0
pandas                    0.18.1              np110py27_0
partd                     0.3.3                    py27_0
path.py                   8.2.1                    py27_0
pbr                       1.8.0                    py27_0
pexpect                   4.0.1                    py27_0
pickleshare               0.5                      py27_0
pip                       8.1.1                    py27_1
pixman                    0.32.6                        0
proj4                     4.9.2                         0
prompt_toolkit            1.0.3                    py27_0
ptyprocess                0.5                      py27_0
pycairo                   1.10.0                   py27_0
pycosat                   0.6.1                    py27_0
pycrypto                  2.6.1                    py27_0
pygments                  2.1.3                    py27_0
pyparsing                 2.1.1                    py27_0
pyproj                    1.9.4                    py27_1
pyqt                      4.11.4                   py27_1
python                    2.7.12                        1
python-dateutil           2.5.3                    py27_0
pytz                      2016.4                   py27_0
pyyaml                    3.11                     py27_1
pyzmq                     15.3.0                   py27_0
qt                        4.8.7                         1
qtconsole                 4.2.1                    py27_0
quickImpt                 1.0                       <pip>
readline                  6.2                           2
requests                  2.9.1                    py27_0
ruamel_yaml               0.11.7                   py27_0
scipy                     0.17.0              np110py27_3
cartopy                   0.13.1              np110py27_0    scitools
geos                      3.4.2                         4    scitools
owslib                    0.10.3                   py27_0    scitools
proj.4                    4.9.1                         1    scitools
pyepsg                    0.2.0                    py27_0    scitools
pyshp                     1.2.3                    py27_0    scitools
shapely                   1.5.13              np110py27_1    scitools
setuptools                20.3                     py27_0
simplegeneric             0.8.1                    py27_0
singledispatch            3.4.0.3                  py27_0
sip                       4.16.9                   py27_0
six                       1.10.0                   py27_0
sqlite                    3.13.0                        0
ssl_match_hostname        3.4.0.2                  py27_1
tblib                     1.3.0                    py27_0
terminado                 0.6                      py27_0
tk                        8.5.18                        0
toolz                     0.7.4                    py27_0
tornado                   4.3                      py27_0
traitlets                 4.2.1                    py27_0
wcwidth                   0.1.7                    py27_0
wheel                     0.29.0                   py27_0
xerces-c                  3.1.4                         0
xz                        5.0.5                         1
yaml                      0.1.6                         0
zeromq                    4.1.4                         0
zlib                      1.2.8                         0
```

Any suggestions? Many thanks!

**Comment by khallock** [comment]
Hi @Yefee,

Based on that output from "conda list", it seems like you have packages from several different conda channels installed. Sometimes multiple packages from different channels can require the same dependency packages, but this can cause issues depending on which versions of those dependencies are installed.

In general, I try to avoid mixing more than two conda channels in a single conda environment in order to avoid issues like this. Could you please try creating and activating a new environment containing pynio using the following commands:
```
conda create --name pynio_test --channel dbrown pynio
source activate pynio_test
```
After verifying that the "dbrown" version of pynio is working, you could try to install some of the other packages that you would like to use alongside pynio.

Also, when importing pynio in Python, the recommended usage is "import Nio". "import nio" may seemingly work, but it would be loading an underlying shared object file, not the full "Nio" Python module.

**Comment by Yefee** [comment]
Hi @khallock ,

Thanks for your information. It has been a loong time since I return to this issue. I tried as you said, but failed again. 

the error message:
```
(pynio_test) che43@yslogin3:/glade/p/work/che43/tools/PyReshaper> python -c "import Nio"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/glade/u/home/che43/miniconda2/envs/pynio_test/lib/python2.7/site-packages/PyNIO/Nio.py", line 83, in <module>
    from nio import *
ImportError: libmfhdf.so.0: cannot open shared object file: No such file or directory
```

**Comment by khallock** [comment]
Hi @Yefee,

There is another version of the PyNIO package available via conda using the "conda-forge" channel. Could you please try creating a new environment and installing pynio using conda-forge and let me know if it works?

conda install -c conda-forge pynio
or
conda create -n testing -c conda-forge pynio

Thanks,
Kevin

**Comment by Yefee** [comment]
Hi @khallock 

I found pynio at conda-forge works. 

Thanks for your help.

**Comment by lvxin233** [comment]
hi knallock,
thanks for your help.
