### ISSUE TITLE
Problems Loading Nio

### ISSUE THREAD

**Issue by bbakernoaa** [NCAR/pynio#9]
I tried to install pynio through anaconda.  I'm having some issues.

After a fresh install 

conda create -c conda-forge pynio

[barryb@aitken ~]$ python 
Python 2.7.12 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import Nio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/aqf/barryb/anaconda2/lib/python2.7/site-packages/PyNIO/Nio.py", line 63, in <module>
    from nio import *
ImportError: /data/aqf/barryb/anaconda2/lib/python2.7/site-packages/PyNIO/../../.././libgeos_c.so.1: ELF file OS ABI invalid

**Comment by khallock** [comment]
Hi @bbakernoaa,

Could you please run "conda env list" and reply with the output?

**Comment by bbakernoaa** [comment]
@khallock sorry I didn't get back to you.  I ended up getting it working but unfortunately it broke again.  

This is the current error I'm getting after a fresh install:

```
python
Python 2.7.13 |Anaconda custom (64-bit)| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import Nio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/aqf/barryb/anaconda2/lib/python2.7/site-packages/PyNIO/Nio.py", line 83, in <module>
    from nio import *
ImportError: libjpeg.so.8: cannot open shared object file: No such file or directory```

Seeing this I tried to install libjpeg8 using conda.  

```
conda install jpeg=8
```

The error message then becomes: 

```
python
Python 2.7.13 |Anaconda custom (64-bit)| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import Nio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/aqf/barryb/anaconda2/lib/python2.7/site-packages/PyNIO/Nio.py", line 83, in <module>
    from nio import *
ImportError: libmfhdf.so.0: cannot open shared object file: No such file or directory
```

**Comment by bbakernoaa** [comment]
Just tried this.  With a fresh install and adding the conda-forge channel first:

```
conda config --add channels conda-forge
conda install pynio pyresample netcdf4

Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /data/aqf/barryb/anaconda2:

The following NEW packages will be INSTALLED:

    basemap:       1.0.8.dev0-np111py27_3          conda-forge
    freexl:        1.0.2-1                         conda-forge
    g2clib:        1.6.0-2                         conda-forge
    gdal:          2.1.3-np111py27_0               conda-forge
    geos:          3.5.1-1                         conda-forge
    giflib:        5.1.4-0                         conda-forge
    hdf4:          4.2.12-0                        conda-forge
    hdfeos2:       2.19.1-7                        conda-forge
    hdfeos5:       5.1.15-6                        conda-forge
    jasper:        1.900.1-4                       conda-forge
    json-c:        0.12-0                          conda-forge
    kealib:        1.4.6-3                         conda-forge
    libdap4:       3.18.3-2                        conda-forge
    libnetcdf:     4.4.1.1-2                       conda-forge
    libpq:         9.5.4-3                         conda-forge
    libspatialite: 4.3.0a-14                       conda-forge
    netcdf4:       1.2.7-np111py27_0               conda-forge
    openjpeg:      2.1.2-2                         conda-forge
    proj4:         4.9.3-2                         conda-forge
    pykdtree:      1.2.1-np111py27_0               conda-forge
    pynio:         1.5.0_beta20160623-np111py27_14 conda-forge
    pyproj:        1.9.5.1-py27_0                  conda-forge
    pyresample:    1.3.0-np111py27_0               conda-forge
    pyshp:         1.2.10-py27_0                   conda-forge
    util-linux:    2.21-0                                     
    xerces-c:      3.1.4-0                                    

The following packages will be SUPERCEDED by a higher-priority channel:

    conda:         4.3.8-py27_0                                --> 4.2.13-py27_0 conda-forge
    conda-env:     2.6.0-0                                     --> 2.6.0-0       conda-forge

Proceed ([y]/n)? y

conda-env-2.6. 100% [###############################################################| Time: 0:00:00 674.40 kB/s
geos-3.5.1-1.t 100% [###############################################################| Time: 0:00:00  26.18 MB/s
giflib-5.1.4-0 100% [###############################################################| Time: 0:00:00  22.99 MB/s
json-c-0.12-0. 100% [###############################################################| Time: 0:00:00  22.01 MB/s
proj4-4.9.3-2. 100% [###############################################################| Time: 0:00:00  26.55 MB/s
util-linux-2.2 100% [###############################################################| Time: 0:00:00   8.04 MB/s
xerces-c-3.1.4 100% [###############################################################| Time: 0:00:00  26.34 MB/s
freexl-1.0.2-1 100% [###############################################################| Time: 0:00:00  15.25 MB/s
hdf4-4.2.12-0. 100% [###############################################################| Time: 0:00:00  22.00 MB/s
jasper-1.900.1 100% [###############################################################| Time: 0:00:00  24.64 MB/s
libpq-9.5.4-3. 100% [###############################################################| Time: 0:00:00  21.77 MB/s
g2clib-1.6.0-2 100% [###############################################################| Time: 0:00:00  16.27 MB/s
hdfeos2-2.19.1 100% [###############################################################| Time: 0:00:00  24.43 MB/s
hdfeos5-5.1.15 100% [###############################################################| Time: 0:00:00  25.68 MB/s
kealib-1.4.6-3 100% [###############################################################| Time: 0:00:00  23.25 MB/s
libdap4-3.18.3 100% [###############################################################| Time: 0:00:00  26.70 MB/s
libnetcdf-4.4. 100% [###############################################################| Time: 0:00:00  26.38 MB/s
libspatialite- 100% [###############################################################| Time: 0:00:00  26.10 MB/s
openjpeg-2.1.2 100% [###############################################################| Time: 0:00:00  15.33 MB/s
pyshp-1.2.10-p 100% [###############################################################| Time: 0:00:00  13.67 MB/s
conda-4.2.13-p 100% [###############################################################| Time: 0:00:00  20.30 MB/s
gdal-2.1.3-np1 100% [###############################################################| Time: 0:00:03  26.55 MB/s
netcdf4-1.2.7- 100% [###############################################################| Time: 0:00:00  19.25 MB/s
pykdtree-1.2.1 100% [###############################################################| Time: 0:00:00  23.70 MB/s
pyproj-1.9.5.1 100% [###############################################################| Time: 0:00:00  26.54 MB/s
pynio-1.5.0_be 100% [###############################################################| Time: 0:00:00  25.43 MB/s
basemap-1.0.8. 100% [###############################################################| Time: 0:00:00  26.52 MB/s
pyresample-1.3 100% [###############################################################| Time: 0:00:00  25.99 MB/s
[barryb@aitken ~]$ python
Python 2.7.13 |Anaconda 4.3.0 (64-bit)| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import Nio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/aqf/barryb/anaconda2/lib/python2.7/site-packages/PyNIO/Nio.py", line 83, in <module>
    from nio import *
ImportError: /data/aqf/barryb/anaconda2/lib/python2.7/site-packages/PyNIO/../../../libgdal.so.20: ELF file OS ABI invalid

**Comment by khallock** [comment]
Hi @bbakernoaa,

In the Traceback output above it appears that you have Anaconda (which includes many conda packages in the root conda environment by default) and that PyNIO is installed in the root conda environment. I suspect there may be some compatibility issue between certain packages on conda-forge and other packages from Anaconda. Would it be possible to use a conda environment for PyNIO?
```
conda create --name pynio_env --channel conda-forge pynio pyresample netcdf4
source activate pynio_env
```

**Comment by bbakernoaa** [comment]
@khallock,

I just tried it.  Got the same error with the conda-forge and libgdal.so.20  :+1: 

```
conda create --name pynio_env --channel conda-forge pynio pyresample netcdf4
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /data/aqf/barryb/anaconda2/envs/pynio_env:

The following NEW packages will be INSTALLED:

    backports_abc:      0.5-py27_0                      conda-forge
    basemap:            1.0.8.dev0-np112py27_3          conda-forge
    ca-certificates:    2017.1.23-0                     conda-forge
    cairo:              1.14.6-4                        conda-forge
    certifi:            2017.1.23-py27_0                conda-forge
    configobj:          5.0.6-py27_0                               
    curl:               7.52.1-0                        conda-forge
    cycler:             0.10.0-py27_0                   conda-forge
    expat:              2.1.0-2                         conda-forge
    fontconfig:         2.12.1-4                        conda-forge
    freetype:           2.7-1                           conda-forge
    freexl:             1.0.2-1                         conda-forge
    functools32:        3.2.3.2-py27_1                  conda-forge
    g2clib:             1.6.0-2                         conda-forge
    gdal:               2.1.3-np112py27_1               conda-forge
    geos:               3.5.1-1                         conda-forge
    gettext:            0.19.7-1                        conda-forge
    giflib:             5.1.4-0                         conda-forge
    glib:               2.51.4-0                        conda-forge
    graphite2:          1.3.9-0                         conda-forge
    harfbuzz:           1.4.3-0                         conda-forge
    hdf4:               4.2.12-0                        conda-forge
    hdf5:               1.8.17-9                        conda-forge
    hdfeos2:            2.19.1-7                        conda-forge
    hdfeos5:            5.1.15-6                        conda-forge
    icu:                58.1-1                          conda-forge
    jasper:             1.900.1-4                       conda-forge
    jpeg:               9b-0                            conda-forge
    json-c:             0.12-0                          conda-forge
    kealib:             1.4.6-3                         conda-forge
    libdap4:            3.18.3-2                        conda-forge
    libffi:             3.2.1-3                         conda-forge
    libgcc:             5.2.0-0                                    
    libgfortran:        3.0.0-1                                    
    libiconv:           1.14-4                          conda-forge
    libnetcdf:          4.4.1.1-2                       conda-forge
    libpng:             1.6.28-0                        conda-forge
    libpq:              9.5.4-3                         conda-forge
    libspatialite:      4.3.0a-14                       conda-forge
    libtiff:            4.0.6-7                         conda-forge
    libxml2:            2.9.4-4                         conda-forge
    matplotlib:         2.0.0-np112py27_2               conda-forge
    mkl:                2017.0.1-0                                 
    ncurses:            5.9-10                          conda-forge
    netcdf4:            1.2.7-np112py27_0               conda-forge
    numexpr:            2.6.2-np112py27_0               conda-forge
    numpy:              1.12.0-py27_0                              
    olefile:            0.44-py27_0                     conda-forge
    openjpeg:           2.1.2-2                         conda-forge
    openssl:            1.0.2h-3                        conda-forge
    pango:              1.40.4-0                        conda-forge
    pcre:               8.39-0                          conda-forge
    pillow:             4.0.0-py27_2                    conda-forge
    pip:                9.0.1-py27_0                    conda-forge
    pixman:             0.34.0-0                        conda-forge
    proj4:              4.9.3-2                         conda-forge
    pykdtree:           1.2.1-np112py27_0               conda-forge
    pynio:              1.5.0_beta20160623-np112py27_14 conda-forge
    pyparsing:          2.1.10-py27_0                   conda-forge
    pyproj:             1.9.5.1-py27_0                  conda-forge
    pyqt:               4.11.4-py27_2                   conda-forge
    pyresample:         1.3.0-np112py27_0               conda-forge
    pyshp:              1.2.10-py27_0                   conda-forge
    python:             2.7.12-2                        conda-forge
    python-dateutil:    2.6.0-py27_0                    conda-forge
    pytz:               2016.10-py27_0                  conda-forge
    qt:                 4.8.7-7                         conda-forge
    readline:           6.2-0                           conda-forge
    scipy:              0.18.1-np112py27_1                         
    setuptools:         33.1.0-py27_0                   conda-forge
    singledispatch:     3.4.0.3-py27_0                  conda-forge
    sip:                4.18-py27_1                     conda-forge
    six:                1.10.0-py27_1                   conda-forge
    sqlite:             3.13.0-1                        conda-forge
    ssl_match_hostname: 3.5.0.1-py27_1                  conda-forge
    subprocess32:       3.2.7-py27_0                    conda-forge
    tk:                 8.5.19-1                        conda-forge
    tornado:            4.4.2-py27_0                    conda-forge
    util-linux:         2.21-0                                     
    wheel:              0.29.0-py27_0                   conda-forge
    xerces-c:           3.1.4-3                         conda-forge
    xz:                 5.2.2-0                         conda-forge
    zlib:               1.2.11-0                        conda-forge

Proceed ([y]/n)? y

ca-certificate 100% |###############################################################################################################################################| Time: 0:00:00   2.91 MB/s
expat-2.1.0-2. 100% |###############################################################################################################################################| Time: 0:00:00   2.06 MB/s
geos-3.5.1-1.t 100% |###############################################################################################################################################| Time: 0:00:04   4.15 MB/s
gettext-0.19.7 100% |###############################################################################################################################################| Time: 0:00:00   6.70 MB/s
giflib-5.1.4-0 100% |###############################################################################################################################################| Time: 0:00:00   6.07 MB/s
graphite2-1.3. 100% |###############################################################################################################################################| Time: 0:00:00 426.54 kB/s
icu-58.1-1.tar 100% |###############################################################################################################################################| Time: 0:00:06   3.86 MB/s
jpeg-9b-0.tar. 100% |###############################################################################################################################################| Time: 0:00:00   2.49 MB/s
json-c-0.12-0. 100% |###############################################################################################################################################| Time: 0:00:00   2.21 MB/s
libffi-3.2.1-3 100% |###############################################################################################################################################| Time: 0:00:00   2.14 MB/s
libgcc-5.2.0-0 100% |###############################################################################################################################################| Time: 0:00:00   6.14 MB/s
libgfortran-3. 100% |###############################################################################################################################################| Time: 0:00:00   6.12 MB/s
libiconv-1.14- 100% |###############################################################################################################################################| Time: 0:00:00   3.39 MB/s
mkl-2017.0.1-0 100% |###############################################################################################################################################| Time: 0:00:41   3.20 MB/s
ncurses-5.9-10 100% |###############################################################################################################################################| Time: 0:00:00   7.89 MB/s
pcre-8.39-0.ta 100% |###############################################################################################################################################| Time: 0:00:00   2.05 MB/s
pixman-0.34.0- 100% |###############################################################################################################################################| Time: 0:00:00   8.22 MB/s
proj4-4.9.3-2. 100% |###############################################################################################################################################| Time: 0:00:00   4.22 MB/s
sqlite-3.13.0- 100% |###############################################################################################################################################| Time: 0:00:01   2.79 MB/s
tk-8.5.19-1.ta 100% |###############################################################################################################################################| Time: 0:00:00   6.98 MB/s
util-linux-2.2 100% |###############################################################################################################################################| Time: 0:00:00   2.86 MB/s
xz-5.2.2-0.tar 100% |###############################################################################################################################################| Time: 0:00:00   5.26 MB/s
zlib-1.2.11-0. 100% |###############################################################################################################################################| Time: 0:00:00 816.08 kB/s
freexl-1.0.2-1 100% |###############################################################################################################################################| Time: 0:00:00   1.25 MB/s
glib-2.51.4-0. 100% |###############################################################################################################################################| Time: 0:00:00   8.45 MB/s
hdf4-4.2.12-0. 100% |###############################################################################################################################################| Time: 0:00:00  10.42 MB/s
hdf5-1.8.17-9. 100% |###############################################################################################################################################| Time: 0:00:00   7.43 MB/s
jasper-1.900.1 100% |###############################################################################################################################################| Time: 0:00:00   6.08 MB/s
libpng-1.6.28- 100% |###############################################################################################################################################| Time: 0:00:00   5.49 MB/s
libtiff-4.0.6- 100% |###############################################################################################################################################| Time: 0:00:00   6.07 MB/s
libxml2-2.9.4- 100% |###############################################################################################################################################| Time: 0:00:01   2.87 MB/s
openssl-1.0.2h 100% |###############################################################################################################################################| Time: 0:00:00   4.71 MB/s
readline-6.2-0 100% |###############################################################################################################################################| Time: 0:00:00   2.00 MB/s
xerces-c-3.1.4 100% |###############################################################################################################################################| Time: 0:00:00   5.18 MB/s
curl-7.52.1-0. 100% |###############################################################################################################################################| Time: 0:00:00   7.16 MB/s
freetype-2.7-1 100% |###############################################################################################################################################| Time: 0:00:00   4.98 MB/s
g2clib-1.6.0-2 100% |###############################################################################################################################################| Time: 0:00:00 467.29 kB/s
hdfeos2-2.19.1 100% |###############################################################################################################################################| Time: 0:00:00 401.34 kB/s
hdfeos5-5.1.15 100% |###############################################################################################################################################| Time: 0:00:00   3.09 MB/s
kealib-1.4.6-3 100% |###############################################################################################################################################| Time: 0:00:00   3.86 MB/s
libpq-9.5.4-3. 100% |###############################################################################################################################################| Time: 0:00:00   4.18 MB/s
libspatialite- 100% |###############################################################################################################################################| Time: 0:00:01   4.18 MB/s
openjpeg-2.1.2 100% |###############################################################################################################################################| Time: 0:00:00   5.15 MB/s
python-2.7.12- 100% |###############################################################################################################################################| Time: 0:00:03   3.79 MB/s
backports_abc- 100% |###############################################################################################################################################| Time: 0:00:00   3.95 MB/s
certifi-2017.1 100% |###############################################################################################################################################| Time: 0:00:00   8.73 MB/s
fontconfig-2.1 100% |###############################################################################################################################################| Time: 0:00:00   4.96 MB/s
functools32-3. 100% |###############################################################################################################################################| Time: 0:00:00   9.61 MB/s
libdap4-3.18.3 100% |###############################################################################################################################################| Time: 0:00:03   4.23 MB/s
libnetcdf-4.4. 100% |###############################################################################################################################################| Time: 0:00:00   4.94 MB/s
numpy-1.12.0-p 100% |###############################################################################################################################################| Time: 0:00:01   3.67 MB/s
olefile-0.44-p 100% |###############################################################################################################################################| Time: 0:00:00   2.30 MB/s
pyparsing-2.1. 100% |###############################################################################################################################################| Time: 0:00:00   4.26 MB/s
pyshp-1.2.10-p 100% |###############################################################################################################################################| Time: 0:00:00  13.50 MB/s
pytz-2016.10-p 100% |###############################################################################################################################################| Time: 0:00:00   3.52 MB/s
sip-4.18-py27_ 100% |###############################################################################################################################################| Time: 0:00:00   2.55 MB/s
six-1.10.0-py2 100% |###############################################################################################################################################| Time: 0:00:00   9.49 MB/s
ssl_match_host 100% |###############################################################################################################################################| Time: 0:00:00 731.03 kB/s
subprocess32-3 100% |###############################################################################################################################################| Time: 0:00:00   4.46 MB/s
cairo-1.14.6-4 100% |###############################################################################################################################################| Time: 0:00:00   2.26 MB/s
configobj-5.0. 100% |###############################################################################################################################################| Time: 0:00:00   4.59 MB/s
cycler-0.10.0- 100% |###############################################################################################################################################| Time: 0:00:00   7.69 MB/s
gdal-2.1.3-np1 100% |###############################################################################################################################################| Time: 0:00:13   6.25 MB/s
numexpr-2.6.2- 100% |###############################################################################################################################################| Time: 0:00:00   4.68 MB/s
pillow-4.0.0-p 100% |###############################################################################################################################################| Time: 0:00:00   5.45 MB/s
pykdtree-1.2.1 100% |###############################################################################################################################################| Time: 0:00:00   7.09 MB/s
pyproj-1.9.5.1 100% |###############################################################################################################################################| Time: 0:00:00   8.32 MB/s
python-dateuti 100% |###############################################################################################################################################| Time: 0:00:00  20.43 MB/s
scipy-0.18.1-n 100% |###############################################################################################################################################| Time: 0:00:04   7.51 MB/s
setuptools-33. 100% |###############################################################################################################################################| Time: 0:00:00   7.61 MB/s
singledispatch 100% |###############################################################################################################################################| Time: 0:00:00   6.30 MB/s
harfbuzz-1.4.3 100% |###############################################################################################################################################| Time: 0:00:00  15.47 MB/s
netcdf4-1.2.7- 100% |###############################################################################################################################################| Time: 0:00:00  16.76 MB/s
pynio-1.5.0_be 100% |###############################################################################################################################################| Time: 0:00:00  13.15 MB/s
tornado-4.4.2- 100% |###############################################################################################################################################| Time: 0:00:00  13.10 MB/s
wheel-0.29.0-p 100% |###############################################################################################################################################| Time: 0:00:00  19.26 MB/s
pango-1.40.4-0 100% |###############################################################################################################################################| Time: 0:00:00  14.17 MB/s
pip-9.0.1-py27 100% |###############################################################################################################################################| Time: 0:00:00  13.22 MB/s
qt-4.8.7-7.tar 100% |###############################################################################################################################################| Time: 0:00:01  18.59 MB/s
pyqt-4.11.4-py 100% |###############################################################################################################################################| Time: 0:00:00  24.75 MB/s
matplotlib-2.0 100% |###############################################################################################################################################| Time: 0:00:00  24.17 MB/s
basemap-1.0.8. 100% |###############################################################################################################################################| Time: 0:00:00  25.05 MB/s
pyresample-1.3 100% |###############################################################################################################################################| Time: 0:00:00  25.59 MB/s
#
# To activate this environment, use:
# > source activate pynio_env
#
# To deactivate this environment, use:
# > source deactivate pynio_env
#

[barryb@aitken ~]$ source activate pynio_env
(pynio_env) [barryb@aitken ~]$ python
Python 2.7.12 | packaged by conda-forge | (default, Feb  9 2017, 14:36:30) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import Nio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/aqf/barryb/anaconda2/envs/pynio_env/lib/python2.7/site-packages/PyNIO/Nio.py", line 83, in <module>
    from nio import *
ImportError: /data/aqf/barryb/anaconda2/envs/pynio_env/lib/python2.7/site-packages/PyNIO/../../../libgdal.so.20: ELF file OS ABI invalid
>>> exit()
(pynio_env) ```

**Comment by khallock** [comment]
@bbakernoaa,

That's odd, I wonder if there's something wrong with the gdal package. Could you please run `ldd /data/aqf/barryb/anaconda2/envs/pynio_env/lib/libgdal.so.20`?

Also, what Linux distribution are you using?

**Comment by bbakernoaa** [comment]
out of ldd:

```
(pynio_env) [barryb@aitken ~]$ ldd /data/aqf/barryb/anaconda2/envs/pynio_env/lib/libgdal.so.20
	not a dynamic executable
```

and linux distribution:

```
lsb_release -a
LSB Version:	:core-4.0-amd64:core-4.0-ia32:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-ia32:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-ia32:printing-4.0-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 5.11 (Tikanga)
Release:	5.11
Codename:	Tikanga
```

**Comment by khallock** [comment]
@bbakernoaa,

This is starting to make sense... I'm not entirely sure why, but some of the conda-forge packages are incompatible with versions of RHEL/CentOS below 6.

conda-forge's build environment uses CentOS 6.8, so it seems like some of the shared objects (libgdal.so.20 for example) created in that environment are not being recognized on your RHEL 5.11 machine. Would it be possible to update this machine to a newer version of Red Hat, and if not is there another machine you could try running PyNIO on?

**Comment by bbakernoaa** [comment]
There is another machine I have access to where I can perform these.  However, I'd still like to find a work around for this machine as there are some other users who use a tool I've built that relies on PyNIO.  Is it possible to get the dbrown or NCAR channels to work?

**Comment by marylhaley** [comment]
We've been trying a number of things to get conda and our software to work
in this older Linux environment, and it's proving to be rather problematic.

Kevin helped me install a CentOS 5.x VM on my Mac box. I will try to build
PyNIO and PyNGL on it outside of the conda environment. I'm also going to
use this opportunity to build a binary for NCL V6.4.0. You will hopefully
be able to use this special PyNGL/PyNIO build with your conda environment.

I have to caution that at some point we will be unable to support older
versions of Linux. This particular version is several years old and it
looks like they may be dropping support for it soon.

**Comment by bbakernoaa** [comment]
@marylhaley 

I'm going to try installing it on the NCEP machines and go from there. I'm currently building it on a small server in our lab.  I'd still like to find a solution if possible.  I have been able to get it working before.  Its just a little touchy.  

I'm mainly worried about PyNIO as it integrates nicely with xarray.

**Comment by david-ian-brown** [comment]
I was using a CentOS 5 VM on Mac for a test conda build of PyNIO when I was
maintaining the dbrown channel. I would copy the conda build to each other
Linux VM that I was testing to make sure it was a "universal" Linux build.
Anyway it is still around and could be updated if it might be useful at
this point.

**Comment by bbakernoaa** [comment]
@david-ian-brown

This would be useful for me. I use this on NCEP production machines as well and I am having trouble getting it running on there as well.

**Comment by david-ian-brown** [comment]
Hi Barry,

I just uploaded a new Centos5-built version of PyNIO to the dbrown channel.
I tested downloading it along with xarray in a new conda environment on the
Centos 5 VM. I was able to import both packages. Hopefully it will work for
you as well:

conda create -n pynio-test -c dbrown pynio xarray

 -dave

**Comment by bbakernoaa** [comment]
Awesome! Thanks @david-ian-brown
